### ISSUE TITLE
Unable to use this with Emacs 24 (built from github repo) and org 20120206

### ISSUE THREAD

**Issue by photex** [baohaojun/org-jira#2]
Error receive:
Wrong type argument: processp, nil

Once I get this issue, it actually affects a great deal of the rest of Emacs. I had to restart emacs with any initialization of org-jira removed from my init.el

Let me know what other info I can provide.

Cheers,
Chip

**Comment by landgraf** [comment]
I have same issue with
Powered By @Atlassian JIRA  6.4.11

**Comment by baohaojun** [comment]
Org-jira have now restapi support a while ago, so please try that version instead. Checkout the restapi branch.
