### ISSUE TITLE
soap-load-wsdl-from-url: Error retrieving WSDL: 404

### ISSUE THREAD

**Issue by securelord** [baohaojun/org-jira#34]
My jira url: https://crm-ocean.atlassian.net
I send right login/password.
But I get this error: soap-load-wsdl-from-url: Error retrieving WSDL: 404

**Comment by baohaojun** [comment]
Err, have your site configured to allow soap connection? If not, you need ask your administrator to configure it first. If it's already configured, then you need do a little emacs debugging to find out which url it is visiting, maybe you have configured a wrong url or something?
