### ISSUE TITLE
JIRA 7.0 doesn't allow SOAP anymore, only REST

### ISSUE THREAD

**Issue by pokkie** [baohaojun/org-jira#35]
We are using JIRA 7.0 and it no longer supports SOAP (see link below:
https://developer.atlassian.com/jiradev/latest-updates/soap-and-xml-rpc-api-deprecation-notice).

Kindly request that org-jira be modified to accommodate the changes.

**Comment by baohaojun** [comment]
OK, started working on it..

**Comment by To1ne** [comment]
I would love this.
For now I've asked our admin to enable SOAP:  https://confluence.atlassian.com/jira/configuring-jira-options-185729544.html "Accept remote API calls"

**Comment by thearthur** [comment]
@To1ne This does not work on the jira 7+ because the option to enable it no longer exists

**Comment by baohaojun** [comment]
I will close this issue now, there have been some basic rest support in the restapi branch.

I don't dare to push it to master, because it will probably break many people's org-jira who are still using soap.

See https://github.com/baohaojun/org-jira/commit/38bf3a0f5668d92a21e1e296ba407c98f4b2e28c for more details.

**Comment by To1ne** [comment]
Wow, super!

But I am having trouble installing: 

> Symbol's function definition is void: require-package

**Comment by To1ne** [comment]
But I got it working by manually removing the `require-package` line.
Now you have made the basic layer, maybe if I find some time I'll try to look at the worklog feature.

**Comment by baohaojun** [comment]
Right, I will remove that line.

Thanks:)

**Comment by alf** [comment]
This is awesome. Only thing missing now is to make this available on melpa.

Maybe this could be exposed as a different package to avoid breaking peoples setup?

**Comment by alf** [comment]
In case anyone is interested, I installed the rest-version of org-jira using quelpa and the following recipe:

`(quelpa '(org-jira :fetcher github :repo "baohaojun/org-jira" :branch "restapi"))`
