### ISSUE TITLE
Cannot add comment in restapi branch

### ISSUE THREAD

**Issue by linc01n** [baohaojun/org-jira#36]
I try to follow the youtube video to create a comment to my jira ticket. But I received 
```
REQUEST [error] Error (error) while connecting to https://...rest/api/2/issue/.../comment.
```

And it seems the API endpoint is not correct.
https://github.com/baohaojun/org-jira/blob/38bf3a0f5668d92a21e1e296ba407c98f4b2e28c/jiralib.el#L245

According to JIRA API doc it should be without comment at the end.

https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-add-comment

**Comment by baohaojun** [comment]
You are right. It's a typo, used the wrong http verb.
