### ISSUE TITLE
SOAP is no longer available, and the restapi branch is completely broken (PR here fixes)

### ISSUE THREAD

**Issue by ahungry** [baohaojun/org-jira#53]
I have a PR here:

https://github.com/baohaojun/org-jira/pull/52

This repository looks somewhat unmaintained, so if this goes unanswered for too long, and if anyone would like, I'll look into taking over as primary maintainer on MELPA and get it linked up to my fork here:

https://github.com/ahungry/org-jira

**Comment by baohaojun** [comment]
Ahangry, please go ahead and take over with my blessing. I myself have not used Jira for the last 3 years. Just renewed my old Jira License to test your PR. It works and I really liked your idea to get the list of assignable users😄.

**Comment by ahungry** [comment]
Awesome, thanks @baohaojun - if you'd like to keep the MELPA repo pointed here and just merge in changes as I make them, that is fine. 

If you'd prefer that MELPA point to my version of the repository, you just need to let the MELPA people know to update, or alternatively you can also add me as a github user with push/merge access directly on this repo of yours.

**Comment by baohaojun** [comment]
@ahungry I have created a pull request to point melpa to your repository. Please let me know if there are other things that I need to do😊.

**Comment by ahungry** [comment]
Awesome, that should be everything, thanks @baohaojun !

**Comment by ahungry** [comment]
(and thanks for all your work on the project!)
