### ISSUE TITLE
Add way to log work

### ISSUE THREAD

**Issue by slackorama** [baohaojun/org-jira#6]
We use the work log prettily heavily here. Any plans to add the ability to update estimates and log hours worked?

**Comment by asachs** [comment]
I see that jiralib.el now has addWorklogAndAutoAdjustRemainingEstimate, would it be possible to have a look at adding worklog ? Thx.

**Comment by agzam** [comment]
yeah this feature so much needed.

**Comment by baohaojun** [comment]
Added some rudimentary worklog support
